config/routes.rb
BaseApp::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "pages/index"

  match "/admin" => "admin/base#index", :as => "admin"

  namespace "admin" do

    resources :users

  end

  root :to => "pages#index"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/role.rb
class Role < ActiveRecord::Base

  has_and_belongs_to_many :users

  def self.admin
    find_or_create_by_name("admin")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_and_belongs_to_many :roles

  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end

  def make_admin
    self.roles << Role.admin
  end

  def revoke_admin
    self.roles.delete(Role.admin)
  end

  def admin?
    role?(:admin)
  end

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token['info']
    if user = User.find_by_email(data["email"])
      user
    else # Create a user with a stub password.
      User.create!(:email => data["email"], :password => Devise.friendly_token[0,20])
    end
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  before_filter :require_admin
  layout "admin"

  def index
  end

  protected

  def require_admin
    unless current_user.try(:admin?)
      render404 and return false
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def render404
    render :file => File.join(Rails.root, 'public', '404.html'), :status => 404, :layout => false
    return true
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, { :sort => column, :direction => direction }, { :class => css_class }
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/base/index.html.erb
<h2>Dashboard</h2>

app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<%= form_for [:admin, @user], :html => { :class => "well" } do |f| -%>

  <%= f.error_messages %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  </br>

  <%= f.submit "Update", :class => "btn" %>

<% end -%>

app/views/admin/users/index.html.erb
<h1>Users</h1>

<%= form_for @search, :url => admin_users_path, :html => { :method => :get, :class => "well form-search" } do |f| %>
  <%= f.text_field :email_contains, :class => "input-medium search-query" %>
  <%= f.submit "Search", :class => "btn" %>
<% end %>

<table class="sortable table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th><%= sortable "id" %></th>
      <th><%= sortable "email" %></th>
      <th><%= sortable "created_at", "Signed up" %></th>
      <th><%= sortable "sign_in_count", "Times signed in" %></th>
      <th><%= sortable "last_sign_in_at", "Last signed in" %></th>
      <th><%= sortable "last_sign_in_ip", "Last sign in IP" %></th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr class="user">
        <td><%= link_to(user.id, admin_user_path(user)) %></td>
        <td><%= link_to(user.email, admin_user_path(user)) %></td>
        <td><%= l( user.created_at, :format => :short_date ) %></td>
        <td><%= user.sign_in_count %></td>
        <td><%= l( user.last_sign_in_at, :format => :long_date ) %></td>
        <td><%= user.last_sign_in_ip %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Destroy', admin_user_path(user), :data => { :confirm => 'Are you sure?' }, :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>

app/views/admin/users/show.html.erb
<dl class="dl-horizontal">

  <dt>Email</dt>
  <dd><%= @user.email %></dd>

  <dt>Sign in count</dt>
  <dd><%= @user.sign_in_count %></dd>

  <dt>Last sign in at</dt>
  <dd><%= l( @user.last_sign_in_at, :format => :long_date ) %></dd>

  <dt>Last sign in IP</dt>
  <dd><%= @user.last_sign_in_ip %></dd>

  <dt>Created at</dt>
  <dd><%= l( @user.created_at, :format => :long_date ) %></dd>

  <dt>Updated at</dt>
  <dd><%= l( @user.updated_at, :format => :long_date ) %></dd>

</dl>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <title>Baseapp Activeadmin - Admin Dashboard</title>

    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>

    <%= csrf_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= yield :head %>

  </head>

  <body>

    <%= render "layouts/admin/main_nav" %>

    <div class="container">

    <%= render "layouts/application/flash_messages" %>

      <%= yield %>

    </div>

  </body>

</html>

app/views/layouts/admin/_main_nav.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">

      <%= link_to "Moving revies companies", admin_path, :class => "brand" %>

      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="nav-collapse">
        <ul class="nav pull-right">
          <li><%= link_to("Users", admin_users_path) %></li>
          <li><%= link_to("Exit →", root_path) %></li>
        </ul>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>

    <title>Baseapp - Active Admin</title>

    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>

    <%= csrf_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= yield :head %>

  </head>

  <body>

    <%= render "layouts/application/header" %>

    <div class="container">

      <%= render "layouts/application/flash_messages" %>

      <%= yield %>

    </div>

  </body>

</html>

app/views/layouts/application/_flash_messages.html.erb
<% if notice %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>

<% if alert %>
  <div class="alert alert-error"><p><%= alert %></p></div>
<% end %>

app/views/layouts/application/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">

      <%= link_to "BaseApp - Active-admin", root_path, :class => "brand" %>

      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="nav-collapse">
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <li><%= link_to "Admin", admin_path %></li>
            <% end %>
            <li><%= link_to "Sign out", destroy_user_session_path %></li>
            <li><%= link_to "Settings", edit_user_registration_path %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
            <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
          <% end -%>
        </ul>
      </div>

    </div>
  </div>
</div>

app/views/pages/index.html.erb
<h1>Welcome <%= current_user.email if current_user %></h1>